export const sampleModel1 = {
  id: 'duplex',
  src: './models/duplex/scene.gltf',
  metaModelSrc: './metaModels/duplex/metaModel.json',
  edges: true,
};

export const sampleModel2 = {
  id: 'OTCConferenceCenter',
  src: './models/OTCConferenceCenter/scene.gltf',
  metaModelSrc: './metaModels/OTCConferenceCenter/metaModel.json',
  edges: true,
};

export const sampleModel3 = {
  id: 'schependomlaan',
  src: './models/schependomlaan/scene.gltf',
  metaModelSrc: './metaModels/schependomlaan/metaModel.json',
  edges: true,
};

export const xktModel = {
  id: 'xkt-model',
  src: './xkt/duplex.xkt',
  metaModelSrc: './xkt/duplex.json',
  edges: true,
};

export const hooksModel = {
  id: 'xkt-model',
  src: './xkt/duplex.xkt',
  metaModelSrc: './xkt/duplex.json',
  edges: true,
};

export const hooksModelv2 = {
  id: 'xkt-model-v2',
  src: './xkt/duplex.xkt',
  metaModelSrc: './xkt/duplex.json',
  edges: true,
  position: [10, 0, 0],
};

export const hooksSchep = {
  id: 'xkt-schependomlaan',
  src: './xkt/schependomlaan.xkt',
  metaModelSrc: './xkt/schependomlaan.json',
  edges: true,
};

export const holterTower = {
  id: 'holter-tower',
  src: './xkt/HolterTower.xkt',
  metaModelSrc: './xkt/HolterTower.json',
  edges: true,
};

export const models = {
  duplex: { label: 'Duplex', model: hooksModel },
  duplex2: {
    label: 'Duplex 2',
    model: hooksModel,
    guids: [
      ['1CZILmCaHETO8tf3SgGEXu'],
      ['0jf0rYHfX3RAB3bSIRjmoa', '2O2Fr$t4X7Zf8NOew3FLOH'],
      [
        '0pNy6pOyf7JPmXRLgxs3sW',
        '0jf0rYHfX3RAB3bSIRjmoa',
        '2O2Fr$t4X7Zf8NOew3FLOH',
      ],
    ],
  },
  schep: {
    label: 'Schependomlaan',
    model: hooksSchep,
    guids: [
      ['2sMqdqIU5BOBeQp_S3Hjru'],
      [
        '1nOs6Hg0v9fR$sLR1LjIyX',
        '3vSAOyJwTEhQMEIJ6D9qRY',
        '1a49H1hof5wg_s62YvIj$u',
        '2501ntWb95m8MEJo4qrYny',
        '1HNUZLqr52MQIS8JLIpeyr',
        '3yL4PuBWf5GQngGRpOzQj0',
        '2CVrp1qDn4igzjEOaRy1At',
        '1c9iYd1ID6_8SdfF0_$1oL',
        '3rCiBKKhrDwwbew3HLeWaY',
        '24n0GKaSvFeRV3aNSSwJju',
        '1OnyTz3nHAl89yfXGn_mxA',
        '0dG$USXzf0kfosAbNzx0hZ',
        '2ccM307sn8XeBTwsFKE_pR',
        '2Ye2fKnjXAEftAAecRMNfV',
        '2QLBwuZDfEmuESkiT_yymc',
        '0aWtcM$1j1$wMs6qq3amY0',
        '21JedoyDf1jg7ixONhPH5B',
        '1o34KGWg5AnRTiJOhwQVdk',
        '0m0_V5iFz0993Gy0YjDTTT',
        '3f3PNjEKnD0vZTIofateh2',
        '1bxNK1wJ15XRDckLWQ$BAb',
        '3EDZcM$kn05hoHQ$Z2Vy3d',
        '1n2fUvkDb5$uMdMN$ImRfp',
        '2JP$Vh$OrBn8WddLabs41k',
        '0thyQFjPX45OCdLCm3UMpK',
        '1Hv1uFMHTCJ9Q$UWKGXCNB',
        '2i_cekBh9Av8P5LKYyoUPb',
        '3eiwfebPz6aBJmLNliMSzQ',
        '1O9Uq4qWPFXx76ALAUin0I',
        '3Vnlo777D6sear4VnH98Ey',
        '1PIXKKGbjAhveqygt5d$RV',
        '1ZKphijRv5aQMN2BPxf7bL',
        '0zCNOX7Q93$xXgBkmGhGey',
        '3THh6wol9DE9p0sKC2_JQR',
        '1oISTbKmL9mfZhmsVEb8hJ',
        '00IbOoI7nFSxfp71ZyLBPm',
        '1ixfSQr9n76xc3$_jdjyOM',
        '0j3ypi4UzFcQ6as7zS7nt8',
        '3ig8lYbDr8gAJsEpAqMubV',
        '0jNuu$i_rD2eUoRxpITzh5',
        '0lc$v_NHjC_xBVfczhz9SK',
        '3oDHF87SD6GB$hBtQMlz7t',
        '2f0$QVByX6ugBTFoMIOEvG',
        '37_P0I4rjCSP6yY7b9oPCb',
        '10MxXhTT99LQ0GlRLBqlO3',
        '3UqAkIwpHEvuKm0l0k$CKt',
        '0nMFjIkQb8nO7pDrrZbNb_',
        '3QJiKD5p93qgcUxHX8_Z7j',
        '0sN$ROEPr71OXQ86YpsVkj',
        '3UWW7y9uTD78thZQ1AADnu',
        '2ON6EcLMD0$O2ZGZgwvXfd',
        '2K3xEFMCn8Oe$qGTeRQqLG',
        '00nskTKeH6WOgaqMmwF3pp',
        '0HQQO2$RT5NxjAYqu6dRxV',
        '39pO7ncAnD5w5sgzGgcfcf',
        '2MzOJGCZbCuh2oTKejJas_',
        '0M6fb3N3rBghp24veh83Nr',
        '2fMb5HmwrADxi44qQ_8H2J',
        '1ARCkaiqTCdheZNfSbvLCm',
        '3MpbjSJ79AF8GSoW6uAzc0',
        '3aUxcoO_j3tfpBZz8KhVDA',
        '1ZgIIxjwjBBBxWK2odqmNt',
        '2FwhScHlD1lf2P0_fxWpdF',
        '3KZ1A31pLDZgv61Pr5ILuZ',
        '1AAprqPif3muSW78GUrrAQ',
        '0CDXLiWLH6_eUKGAQGeEX9',
        '25jnbRuOH3yR0Vnxbrf4Ey',
        '2DXRwGxjb2hAD7EnaJghPn',
        '0vISlVtTXFjgpC$RZewh3J',
        '1W3I3R2x19bfOBW_WD4sxL',
        '2onr4hRYf5AOPdEOcMaAGr',
        '2svKHCTfTCJeS$mVvXojdH',
        '3whW5kRxz9uPvew6tBRVkS',
        '1L189paHTCx8_OpSrSK35v',
        '3LgbXHWjL33wXWkwFrdttj',
        '033KaR1kL86e6qeKWXcfxF',
        '2K7JRliz9F8R2WKcFfDhY9',
        '3pu87UvP13p9E_$8QPMNkM',
        '0bBhbWDY123eBffCPFwaaU',
        '3BxVQne458OBfuo$8pV1HD',
        '3r$IV2dbHAOuD3XJ$Kd92o',
        '2UtSx95dv3JRuY4Yu9CqPb',
        '0H6WZKwMz2yfLBeSGHTQGE',
        '1qbDTWHmL3WOviuiQtPseV',
        '3cAt3keOr5IAqWcOfbuNAx',
        '1nZz9768j4pAFS7rcljTUA',
        '3k4bKKm$v3NhnNEkaCaT8m',
        '1Smy9UIZz0PuzXFjRN_8t9',
        '3KLNE8pAj368INMalwxWdL',
        '27UY7Jvcf9lwFMjSTxNQnh',
        '3ZT2xJqOf95AGfYHSE9vsv',
        '251MpPi5nDfgW6sNnBdgEm',
        '0PbuAnDOv9MROtn6VXvlS9',
        '2Q3H7PK0j5Ux$7$peFmB5R',
        '0lV3_6JX5Dn8WMYQWopUL4',
        '3GkVJkbxnCbBdkElcpIobH',
        '2KaTlAZm90L8ylCN2TaJL1',
        '3nFC64uPPAXefSRxq6JPqA',
        '0OwiY0E_H6nAVOZ5L_gs8R',
        '3l4LEWO$z6PR20zTCo0DFf',
        '09TMGnoXvA0QiwTfqmChQ0',
        '06FuADHCz36hBoAywogP5m',
        '2KDiiUOLb3WAKWvMvjXliZ',
        '3HN6IBOw1BKQP$d73uzLdY',
        '0mvjiuGlP7MPeepglQyQNO',
        '2pbiLPvmT6YhtHLcp58S99',
        '2D4tEzzn96KxhitMgTCmsY',
        '0I38IR49XCjeOw$CuPT3ZI',
        '24_ACX2uf3DQHvDbd2z98c',
        '1zGerOGCD5Rvedyb1slEai',
        '2LY4pySAHCMRiOW6gZJB2k',
        '3nSAIsE4n8sBWbxoPQ5dy9',
        '0HIb$9Byf2ZBlCjcOu2Qju',
        '01nWzpou174OweRJuvV0oN',
        '1j$4rRHLz1HQbuBG5lkdFZ',
        '0ahwXaU353xOITjLmOzUt4',
        '16qUObfsXFShDHc3t7gGIZ',
        '0p5DTahObB4gZyJfnNXgRR',
        '1MmZYEKF5Fjg0U$Axhtgap',
        '2MO6G9ns58cQ7xbcbLdz06',
        '0Yg$3eCdj5TfoJlEv2sNBN',
        '390EuePXb0OhjRV8d6hXqE',
        '30PtVh$Bz9RxwCgystZdJF',
        '1fGrQYIYP4IxWBDX0HVDV6',
        '0j2Oz3Bjz8g95L4tRLEvJR',
        '2du1puVD9BDw_hpi4B0Nz1',
        '07CJSAM0fDC9txPX6iBpVL',
        '0KEODzPAvAYfDEnWfvxPSf',
        '2japyIy5LCh9FVOdjL5sLr',
        '3rm7AtWY9BCBlzkw8$VplC',
        '0oDaXCEUb4qRApwJFIFZGb',
        '02pJnwninFKefvu_ivlXzM',
        '2SNH8$CzP0tQ4Ndlfu37pR',
      ],
    ],
  },
  holter: { label: 'Holter Tower', model: holterTower },
};
